# ===============
# Header
# ===============
# Navigation menu（斜杠开头表示站点根目录下的路径）
menu:
  Home: /
  Archives: /archives
  About: /about/
# RSS link
rss: /atom.xml
# Path of title banner image of page top
banner: "images/banner.jpg"
# Subtitle of page top
subtitle:
# Header links with icon, specified links will appear at the top right corner of the page
# Each name must correspond to the icon name of Fork Awesome
# https://forkaweso.me/Fork-Awesome/icons/
links:
#  github: https://github.com/your_github_account

# ===============
# Content
# ===============
# "Read More" link at the bottom of excerpted articles. `false` to hide the link.
excerpt_link: Read More
# Enable fancybox
fancybox: true

# ===============
# Footer
# ===============
# Display copyright notice in footer.
copyright:

# ===============
# Sidebar
# ===============
# Sidebar style. You can choose `left`, `right`, `bottom` or `false`.
sidebar: right
# Widgets displaying in sidebar
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# ===============
# Widget behavior
# ===============
archive_type: 'monthly'
show_count: false
# How many posts display in Home page.
recent_posts_limits: 5

# ===============
# Miscellaneous
# ===============
# Google Analytics ID
google_analytics:
gauges_analytics:
# Favicon path
favicon: /favicon.png
# Twitter ID
twitter:
fb_admins:
fb_app_id:

# ===============
# Comment system
# ===============
# Disqus comment system.
disqus_shortname:
# valine comment system. https://valine.js.org
valine:
  enable: false
  appId:
  appKey:
  notify: false
  verify: false
  pageSize: 10
  avatar: mm
  lang: zh-cn
  placeholder: Just go go
  guest_info: nick,mail,link
